[web]
client_id = "1059524177486-6pkol5que1iejjnmmse9keqjgmiq2pqp.apps.googleusercontent.com"
project_id = "concise-rex-442402-b5"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
redirect_uris = ["https://axiomgit-dppnbnhmqnccrv4xcjm3r3.streamlit.app/"]
javascript_origins = ["https://axiomgit-dppnbnhmqnccrv4xcjm3r3.streamlit.app/"]

openai_api_key = "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"
